spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./db/currency
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true